language: node_js
node_js:
  - "7"
install: ./travis-setup.sh
script: ./node_modules/gulp/bin/gulp.js dist && ./node_modules/gulp/bin/gulp.js links
cache:
  directories:
    - travis_phantomjs

env:
  - BUILD_PDF=false
