#!/bin/bash
cd codeclub_lesson_builder
npm install
if [ $? -ne 0 ]; then # try again
  echo "Setup failed, trying one more time."
  # oooh, i'm nasty, but i think this will work out for us two
  rm -fr node_modules
  npm install
fi
cd ..
